version: '3'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - .data/mongo:/data
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    volumes:
      - .data/redis:/data
    restart: always
    ports: 
      - 6379:6379